RESTCallout/src/objects/Integration_Definition__c.object
<CustomObject>
    <fields>
        <fullName>External_Object__c</fullName>
        <defaultValue>false</defaultValue>
        <label>External Object</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HTTP_Method__c</fullName>
        <label>HTTP Method</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Integration Target</label>
        <referenceTo>Integration_Target__c</referenceTo>
        <relationshipLabel>Integration Definitions</relationshipLabel>
        <relationshipName>Integration_Definitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Integration_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Integration User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Method__c</fullName>
        <label>URL Method</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Integration Definition</label>
    <nameField>
        <label>Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RESTCallout/src/objects/Integration_Input__c.object
<CustomObject>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Boolean</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fixed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fixed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integration_Definition__c</fullName>
        <label>Integration Definition</label>
        <referenceTo>Integration_Definition__c</referenceTo>
        <relationshipLabel>Integration Inputs</relationshipLabel>
        <relationshipName>Integration_Inputs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Body</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Header</fullName>
                </value>
                <value>
                    <fullName>URI</fullName>
                </value>
                <value>
                    <fullName>Query Parameter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Integration Input</label>
    <nameField>
        <label>Integration Input Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RESTCallout/src/objects/Integration_Output__c.object
<CustomObject>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Url</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Header_Variable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Header Variable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integration_Definition__c</fullName>
        <label>Integration Definition</label>
        <referenceTo>Integration_Definition__c</referenceTo>
        <relationshipLabel>Integration Outputs</relationshipLabel>
        <relationshipName>Integration_Outputs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Integration Output</label>
    <nameField>
        <label>Integration Output Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Outputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RESTCallout/src/objects/Integration_Target__c.object
<CustomObject>
    <fields>
        <fullName>Integration_User__c</fullName>
        <label>Integration User</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Named_Credentials__c</fullName>
        <label>Named Credentials</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Field_Name__c</fullName>
        <label>User Field Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Integration Target</label>
    <nameField>
        <label>Integration Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RESTCallout/src/classes/RESTCalloutTest.cls
@isTest
private class RESTCalloutTest {
    @isTest
    static void testRESTCallout() {
        Test.setMock(HttpCalloutMock.class, new RESTCalloutMock());
        
        Test.startTest();
         Integration_Target__c IntTarget = new Integration_Target__c();
        
        IntTarget.Name = 'Test Target';
        IntTarget.Named_Credentials__c = 'Test';
        IntTarget.User_Field_Name__c = 'UserName';
        
        Insert IntTarget;
        
        Integration_Definition__c IntDef = new Integration_Definition__c();
        
        IntDef.Integration_Target__c = IntTarget.Id;
        IntDef.Name = 'Blacklist';
        IntDef.External_Object__c = false;
        IntDef.HTTP_Method__c = 'GET';
        IntDef.Integration_User__c = false;
        IntDef.URL_Method__c = 'Test';
        IntDef.Object__c = 'Contact';
        
        Insert IntDef;
        
        Integration_Output__c IntOutput = new Integration_Output__c();
        IntOutput.Name = 'first_name';
        IntOutput.Field_Name__c = 'FirstName';
        IntOutput.Field_Type__c = 'Text';
        IntOutput.Header_Variable__c = false;
        IntOUtput.Integration_Definition__c = IntDef.Id;
        Insert IntOutput;
        
        IntOutput = new Integration_Output__c();
        IntOutput.Name = 'last_name';
        IntOutput.Field_Name__c = 'LastName';
        IntOutput.Field_Type__c = 'Text';
        IntOutput.Header_Variable__c = false;
        IntOUtput.Integration_Definition__c = IntDef.Id;
        Insert IntOutput;
        
        IntOutput = new Integration_Output__c();
        IntOutput.Name = 'BirthPlace';
        IntOutput.Field_Name__c = 'Birth_Town__c';
        IntOutput.Field_Type__c = 'Text';
        IntOutput.Header_Variable__c = true;
        IntOUtput.Integration_Definition__c = IntDef.Id;

        Insert IntOutput;
        
        Integration_Input__c IntInput = new Integration_Input__c();
        IntInput.Name = 'FirstName';
        IntInput.Field_Name__c = 'FirstName';
        IntInput.Field_Type__c = 'Text';
        IntInput.Integration_Definition__c = IntDef.Id;
        IntInput.Fixed__c = false;
        IntInput.Type__c = 'Body';
        Insert IntInput;
   
        IntInput = new Integration_Input__c();
        IntInput.Name = 'FirstName2';
        IntInput.Field_Name__c = 'FirstName';
        IntInput.Field_Type__c = 'Text';
        IntInput.Integration_Definition__c = IntDef.Id;
        IntInput.Fixed__c = false;
        IntInput.Type__c = 'Header';
        Insert IntInput;
  
        IntInput = new Integration_Input__c();
        IntInput.Name = 'Customer.FirstName3';
        IntInput.Field_Name__c = 'FirstName';
        IntInput.Field_Type__c = 'Text';
        IntInput.Integration_Definition__c = IntDef.Id;
        IntInput.Fixed__c = false;
        IntInput.Type__c = 'Body';
        Insert IntInput;
        
        
  
        
        Contact c = new Contact();
        // c.RecordTypeId = '0120Y000000XvWbQAK';
       
        c.FirstName = 'Jack';
        c.LastName = 'van Dijk';
        
        Insert c;
        
        List<Contact> Contacts = [select FirstName, LastName from Contact where Id = :c.ID];
        
        System.assertEquals(1, Contacts.size());
 
        
        RESTDataSourceProvider RESTDP = new RESTDataSourceProvider();
        
        RESTDP.getCapabilities();
        RESTDP.getAuthenticationCapabilities();
        RESTDP.getConnection(null);
        
        Test.stopTest();
   
      
    }

}